name: test

on:
  push:
    branches:
      - main
  workflow_call:


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.52
          args: --disable-all --enable=govet,errcheck,staticcheck,gosimple

      - name: Test code
        run: go test -v ./...
